/* Generated by re2c 1.3 on Fri Sep 18 00:52:43 2020 */
#line 1 "src/sfizz/OpcodeCleanup.re"
/* -*- mode: c++; -*- */
// SPDX-License-Identifier: BSD-2-Clause

// This code is part of the sfizz library and is licensed under a BSD 2-clause
// license. You should have receive a LICENSE.md file along with the code.
// If not, contact the sfizz maintainers at https://github.com/sfztools/sfizz

#include "Opcode.h"
#include "Macros.h"
#include "absl/strings/string_view.h"
#include "absl/strings/str_cat.h"
#include "absl/strings/ascii.h"
#include <string>

namespace sfz {

static std::string cleanUpOpcodeName(absl::string_view rawOpcode, OpcodeScope scope)
{
    std::string opcode { rawOpcode };

    // always convert it to lower case
    absl::AsciiStrToLower(&opcode);

    #line 28 "src/sfizz/OpcodeCleanup.re"

    #define YYMAXNMATCH 4


    const char* YYCURSOR;
    const char* YYMARKER;
    const char* yypmatch[2 * YYMAXNMATCH];
    size_t yynmatch;
    UNUSED(yynmatch);

    const char* yyt1; const char* yyt2; const char* yyt3; const char* yyt4; const char* yyt5; 

    auto group = [&yypmatch](size_t i) -> absl::string_view {
        const char *beg = yypmatch[2 * i];
        const char *end = yypmatch[2 * i + 1];
        return absl::string_view(beg, end - beg);
    };

    #line 50 "src/sfizz/OpcodeCleanup.re"


    //--------------------------------------------------------------------------

    if (scope == kOpcodeScopeRegion) {

    YYCURSOR = opcode.c_str();

    
#line 56 "src/sfizz/OpcodeCleanup.cpp"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '_':
		yyt1 = YYCURSOR;
		goto yy5;
	default:
		yyt1 = YYCURSOR;
		goto yy4;
	}
yy2:
	++YYCURSOR;
yy3:
#line 65 "src/sfizz/OpcodeCleanup.re"
	{
        goto end_region_oncc;
    }
#line 76 "src/sfizz/OpcodeCleanup.cpp"
yy4:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy3;
	goto yy7;
yy5:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:	goto yy3;
	case 'c':	goto yy11;
	default:	goto yy7;
	}
yy6:
	yych = *++YYCURSOR;
yy7:
	switch (yych) {
	case 0x00:	goto yy8;
	case '_':	goto yy9;
	default:	goto yy6;
	}
yy8:
	YYCURSOR = YYMARKER;
	goto yy3;
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy8;
	case '_':	goto yy9;
	case 'c':	goto yy11;
	default:	goto yy6;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy8;
	case '_':	goto yy9;
	case 'c':	goto yy12;
	default:	goto yy6;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy8;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = YYCURSOR;
		goto yy13;
	case '_':	goto yy9;
	default:	goto yy6;
	}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy15;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy13;
	case '_':	goto yy9;
	default:	goto yy6;
	}
yy15:
	++YYCURSOR;
	yynmatch = 3;
	yypmatch[2] = yyt1;
	yypmatch[4] = yyt2;
	yypmatch[0] = yyt1;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = yyt2 - 3;
	yypmatch[5] = YYCURSOR - 1;
#line 60 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat(group(1), "_oncc", group(2));
        goto end_region_oncc;
    }
#line 165 "src/sfizz/OpcodeCleanup.cpp"
}
#line 69 "src/sfizz/OpcodeCleanup.re"


end_region_oncc:
    /* end */;

    } // scope == kOpcodeScopeRegion

    //--------------------------------------------------------------------------

    if (scope == kOpcodeScopeRegion) {

    YYCURSOR = opcode.c_str();

    
#line 182 "src/sfizz/OpcodeCleanup.cpp"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 'a':
		yyt1 = YYCURSOR;
		goto yy21;
	case 'b':	goto yy22;
	case 'c':
		yyt1 = YYCURSOR;
		goto yy23;
	case 'e':
		yyt1 = YYCURSOR;
		goto yy24;
	case 'f':
		yyt1 = YYCURSOR;
		goto yy25;
	case 'g':
		yyt1 = YYCURSOR;
		goto yy26;
	case 'h':	goto yy27;
	case 'l':
		yyt1 = YYCURSOR;
		goto yy28;
	case 'o':	goto yy29;
	case 'p':
		yyt1 = YYCURSOR;
		goto yy30;
	case 'r':
		yyt1 = YYCURSOR;
		goto yy31;
	case 't':
		yyt1 = YYCURSOR;
		goto yy32;
	default:	goto yy19;
	}
yy19:
	++YYCURSOR;
yy20:
#line 176 "src/sfizz/OpcodeCleanup.re"
	{
        goto end_region;
    }
#line 226 "src/sfizz/OpcodeCleanup.cpp"
yy21:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'm':	goto yy33;
	default:	goto yy20;
	}
yy22:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy35;
	default:	goto yy20;
	}
yy23:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'u':	goto yy36;
	default:	goto yy20;
	}
yy24:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'g':	goto yy37;
	case 'q':	goto yy38;
	default:	goto yy20;
	}
yy25:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'i':	goto yy39;
	default:	goto yy20;
	}
yy26:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy40;
	default:	goto yy20;
	}
yy27:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'i':	goto yy41;
	default:	goto yy20;
	}
yy28:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'f':	goto yy42;
	case 'o':	goto yy43;
	default:	goto yy20;
	}
yy29:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'f':	goto yy44;
	case 'n':	goto yy45;
	default:	goto yy20;
	}
yy30:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'i':	goto yy46;
	case 'o':	goto yy47;
	default:	goto yy20;
	}
yy31:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy48;
	default:	goto yy20;
	}
yy32:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'u':	goto yy49;
	default:	goto yy20;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy50;
	default:	goto yy34;
	}
yy34:
	YYCURSOR = YYMARKER;
	goto yy20;
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy51;
	default:	goto yy34;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy52;
	default:	goto yy34;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy53;
	default:	goto yy34;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy55;
	default:	goto yy34;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy57;
	default:	goto yy34;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy58;
	default:	goto yy34;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy59;
	default:	goto yy34;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy60;
	default:	goto yy34;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy61;
	case 'r':	goto yy59;
	default:	goto yy34;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy62;
	default:	goto yy34;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy63;
	default:	goto yy34;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy64;
	default:	goto yy34;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy65;
	default:	goto yy34;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy66;
	default:	goto yy34;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy67;
	default:	goto yy34;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy68;
	case 'l':	goto yy69;
	default:	goto yy34;
	}
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy70;
	default:	goto yy34;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy71;
	default:	goto yy34;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy53;
	case '_':	goto yy72;
	default:	goto yy34;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy55;
	case '_':	goto yy73;
	default:	goto yy34;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = YYCURSOR;
		goto yy74;
	case '_':	goto yy76;
	case 'e':	goto yy68;
	case 'l':	goto yy69;
	case 't':	goto yy77;
	default:	goto yy34;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy78;
	default:	goto yy34;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy79;
	default:	goto yy34;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy80;
	default:	goto yy34;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy82;
	default:	goto yy34;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':
		yyt1 = YYCURSOR;
		goto yy83;
	case 'm':
		yyt1 = YYCURSOR;
		goto yy84;
	default:	goto yy34;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy85;
	case 'l':	goto yy86;
	default:	goto yy34;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy87;
	default:	goto yy34;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy88;
	default:	goto yy34;
	}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy89;
	default:	goto yy34;
	}
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy90;
	default:	goto yy34;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy91;
	default:	goto yy34;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy92;
	default:	goto yy34;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':
		yyt1 = YYCURSOR;
		goto yy93;
	case 'u':
		yyt1 = YYCURSOR;
		goto yy94;
	default:	goto yy34;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy95;
	default:	goto yy34;
	}
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':
		yyt2 = YYCURSOR;
		goto yy96;
	case 'r':
		yyt2 = YYCURSOR;
		goto yy97;
	default:	goto yy34;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':
		yyt2 = YYCURSOR;
		goto yy98;
	case 'f':
		yyt2 = YYCURSOR;
		goto yy99;
	case 'g':
		yyt2 = YYCURSOR;
		goto yy100;
	default:	goto yy34;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy74;
	case 't':	goto yy101;
	default:	goto yy34;
	}
yy76:
	yych = *++YYCURSOR;
	yyt1 = YYCURSOR;
	goto yy105;
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy106;
	default:	goto yy34;
	}
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:
		yyt2 = yyt3 = NULL;
		goto yy107;
	case '_':
		yyt3 = YYCURSOR;
		goto yy109;
	default:	goto yy34;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy111;
	default:	goto yy34;
	}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy80;
	case '_':	goto yy112;
	default:	goto yy34;
	}
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':
		yyt1 = YYCURSOR;
		goto yy113;
	case 'm':
		yyt1 = YYCURSOR;
		goto yy114;
	case 's':
		yyt1 = YYCURSOR;
		goto yy115;
	default:	goto yy34;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy116;
	default:	goto yy34;
	}
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy117;
	default:	goto yy34;
	}
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy118;
	default:	goto yy34;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy118;
	default:	goto yy34;
	}
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy50;
	default:	goto yy34;
	}
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy119;
	default:	goto yy34;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy120;
	default:	goto yy34;
	}
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:
		yyt2 = yyt3 = NULL;
		goto yy121;
	case '_':
		yyt3 = YYCURSOR;
		goto yy123;
	default:	goto yy34;
	}
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy125;
	default:	goto yy34;
	}
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy126;
	default:	goto yy34;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy127;
	default:	goto yy34;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy128;
	default:	goto yy34;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy129;
	default:	goto yy34;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy130;
	default:	goto yy34;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy131;
	default:	goto yy34;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy132;
	default:	goto yy34;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy133;
	default:	goto yy34;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy134;
	default:	goto yy34;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy135;
	default:	goto yy34;
	}
yy102:
	++YYCURSOR;
	yynmatch = 2;
	yypmatch[2] = yyt1;
	yypmatch[0] = yyt1 - 4;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = YYCURSOR - 1;
#line 158 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat("fil1_", group(1));
        goto end_region;
    }
#line 826 "src/sfizz/OpcodeCleanup.cpp"
yy104:
	yych = *++YYCURSOR;
yy105:
	if (yych <= 0x00) goto yy102;
	goto yy104;
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy136;
	default:	goto yy34;
	}
yy107:
	++YYCURSOR;
	yynmatch = 2;
	yypmatch[0] = yyt1;
	yypmatch[2] = yyt3;
	yypmatch[3] = yyt2;
	yypmatch[1] = YYCURSOR;
#line 140 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat("volume", group(1));
        goto end_region;
    }
#line 850 "src/sfizz/OpcodeCleanup.cpp"
yy109:
	yych = *++YYCURSOR;
	if (yych <= 0x00) {
		yyt2 = YYCURSOR;
		goto yy107;
	}
	goto yy109;
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy137;
	default:	goto yy34;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':
		yyt2 = YYCURSOR;
		goto yy138;
	case 'o':
		yyt2 = YYCURSOR;
		goto yy139;
	case 'r':
		yyt2 = YYCURSOR;
		goto yy140;
	case 's':
		yyt2 = YYCURSOR;
		goto yy141;
	case 'w':
		yyt2 = YYCURSOR;
		goto yy142;
	default:	goto yy34;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy143;
	default:	goto yy34;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy144;
	default:	goto yy34;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy145;
	default:	goto yy34;
	}
yy116:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy146;
	goto yy34;
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy148;
	default:	goto yy34;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy149;
	case 'h':	goto yy150;
	default:	goto yy34;
	}
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy151;
	default:	goto yy34;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy152;
	default:	goto yy34;
	}
yy121:
	++YYCURSOR;
	yynmatch = 2;
	yypmatch[0] = yyt1;
	yypmatch[2] = yyt3;
	yypmatch[3] = yyt2;
	yypmatch[1] = YYCURSOR;
#line 144 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat("pitch", group(1));
        goto end_region;
    }
#line 943 "src/sfizz/OpcodeCleanup.cpp"
yy123:
	yych = *++YYCURSOR;
	if (yych <= 0x00) {
		yyt2 = YYCURSOR;
		goto yy121;
	}
	goto yy123;
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':
		yyt2 = YYCURSOR;
		goto yy153;
	case 'd':
		yyt2 = YYCURSOR;
		goto yy154;
	case 'h':
		yyt2 = YYCURSOR;
		goto yy155;
	case 'r':
		yyt2 = YYCURSOR;
		goto yy156;
	case 's':
		yyt2 = YYCURSOR;
		goto yy157;
	default:	goto yy34;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy158;
	default:	goto yy34;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy159;
	default:	goto yy34;
	}
yy128:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy160;
	goto yy34;
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:
		yyt2 = yyt3 = NULL;
		goto yy162;
	case '_':
		yyt3 = YYCURSOR;
		goto yy164;
	default:	goto yy34;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy166;
	default:	goto yy34;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy167;
	default:	goto yy34;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy168;
	default:	goto yy34;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy169;
	default:	goto yy34;
	}
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy170;
	default:	goto yy34;
	}
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy171;
	default:	goto yy34;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy172;
	default:	goto yy34;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy173;
	default:	goto yy34;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy174;
	default:	goto yy34;
	}
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy175;
	default:	goto yy34;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy176;
	case 'e':	goto yy177;
	default:	goto yy34;
	}
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy178;
	default:	goto yy34;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy179;
	default:	goto yy34;
	}
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy180;
	default:	goto yy34;
	}
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy181;
	default:	goto yy34;
	}
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy182;
	default:	goto yy34;
	}
yy146:
	++YYCURSOR;
	yynmatch = 2;
	yypmatch[2] = yyt1;
	yypmatch[0] = yyt1 - 3;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = YYCURSOR - 1;
#line 118 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat("off_", group(1));
        goto end_region;
    }
#line 1107 "src/sfizz/OpcodeCleanup.cpp"
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy116;
	default:	goto yy34;
	}
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy183;
	default:	goto yy34;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy184;
	default:	goto yy34;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy185;
	default:	goto yy34;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy186;
	default:	goto yy34;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy187;
	default:	goto yy34;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy188;
	default:	goto yy34;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy189;
	default:	goto yy34;
	}
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy190;
	default:	goto yy34;
	}
yy157:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy191;
	case 'u':	goto yy192;
	default:	goto yy34;
	}
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':
		yyt2 = YYCURSOR;
		goto yy193;
	case 'f':
		yyt2 = YYCURSOR;
		goto yy194;
	default:	goto yy34;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy128;
	default:	goto yy34;
	}
yy160:
	++YYCURSOR;
	yynmatch = 2;
	yypmatch[2] = yyt1;
	yypmatch[0] = yyt1 - 4;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = YYCURSOR - 1;
#line 122 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat("bend_", group(1));
        goto end_region;
    }
#line 1198 "src/sfizz/OpcodeCleanup.cpp"
yy162:
	++YYCURSOR;
	yynmatch = 2;
	yypmatch[0] = yyt1;
	yypmatch[2] = yyt3;
	yypmatch[3] = yyt2;
	yypmatch[1] = YYCURSOR;
#line 162 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat("cutoff1", group(1));
        goto end_region;
    }
#line 1211 "src/sfizz/OpcodeCleanup.cpp"
yy164:
	yych = *++YYCURSOR;
	if (yych <= 0x00) {
		yyt2 = YYCURSOR;
		goto yy162;
	}
	goto yy164;
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy195;
	default:	goto yy34;
	}
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy196;
	default:	goto yy34;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy197;
	default:	goto yy34;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'q':	goto yy132;
	default:	goto yy34;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy132;
	default:	goto yy34;
	}
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy198;
	default:	goto yy34;
	}
yy172:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy199;
	goto yy34;
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy201;
	default:	goto yy34;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy202;
	default:	goto yy34;
	}
yy175:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy203;
	default:	goto yy34;
	}
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy204;
	default:	goto yy34;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy205;
	default:	goto yy34;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy206;
	default:	goto yy34;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'v':	goto yy207;
	default:	goto yy34;
	}
yy180:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy208;
	goto yy34;
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy180;
	default:	goto yy34;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy210;
	default:	goto yy34;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = YYCURSOR;
		goto yy211;
	default:	goto yy34;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy213;
	default:	goto yy34;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy214;
	default:	goto yy34;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy215;
	default:	goto yy34;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy216;
	default:	goto yy34;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':
	case 'l':	goto yy217;
	default:	goto yy34;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy218;
	default:	goto yy34;
	}
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy219;
	default:	goto yy34;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy220;
	default:	goto yy34;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy221;
	default:	goto yy34;
	}
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy222;
	default:	goto yy34;
	}
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy223;
	case 'r':	goto yy224;
	default:	goto yy34;
	}
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy225;
	default:	goto yy34;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy226;
	default:	goto yy34;
	}
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt3 = YYCURSOR;
		goto yy227;
	default:	goto yy34;
	}
yy198:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy229;
	goto yy34;
yy199:
	++YYCURSOR;
	yynmatch = 1;
	yypmatch[0] = YYCURSOR - 8;
	yypmatch[1] = YYCURSOR;
#line 126 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat("fil1_type");
        goto end_region;
    }
#line 1445 "src/sfizz/OpcodeCleanup.cpp"
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = YYCURSOR;
		goto yy231;
	default:	goto yy34;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy233;
	default:	goto yy34;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy234;
	default:	goto yy34;
	}
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy235;
	default:	goto yy34;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy236;
	default:	goto yy34;
	}
yy206:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy207;
	default:	goto yy34;
	}
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy237;
	default:	goto yy34;
	}
yy208:
	++YYCURSOR;
	yynmatch = 2;
	yypmatch[2] = yyt1;
	yypmatch[0] = yyt1 - 4;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = YYCURSOR - 1;
#line 114 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat("loop_", group(1));
        goto end_region;
    }
#line 1511 "src/sfizz/OpcodeCleanup.cpp"
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy180;
	default:	goto yy34;
	}
yy211:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy238;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy211;
	default:	goto yy34;
	}
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy240;
	default:	goto yy34;
	}
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy241;
	default:	goto yy34;
	}
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy242;
	default:	goto yy34;
	}
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy243;
	default:	goto yy34;
	}
yy217:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy244;
	default:	goto yy34;
	}
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy245;
	default:	goto yy34;
	}
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy246;
	default:	goto yy34;
	}
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy247;
	default:	goto yy34;
	}
yy221:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy248;
	default:	goto yy34;
	}
yy222:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy249;
	default:	goto yy34;
	}
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy250;
	default:	goto yy34;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy251;
	default:	goto yy34;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy252;
	default:	goto yy34;
	}
yy226:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy253;
	default:	goto yy34;
	}
yy227:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy254;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy227;
	default:	goto yy34;
	}
yy229:
	++YYCURSOR;
	yynmatch = 2;
	yypmatch[2] = yyt1;
	yypmatch[0] = yyt1 - 3;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = YYCURSOR - 5;
#line 130 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat("fil", group(1), "_type");
        goto end_region;
    }
#line 1646 "src/sfizz/OpcodeCleanup.cpp"
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy256;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy231;
	default:	goto yy34;
	}
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy258;
	default:	goto yy34;
	}
yy234:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy259;
	default:	goto yy34;
	}
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy237;
	default:	goto yy34;
	}
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy260;
	default:	goto yy34;
	}
yy237:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy261;
	goto yy34;
yy238:
	++YYCURSOR;
	yynmatch = 3;
	yypmatch[4] = yyt1;
	yypmatch[0] = yyt1 - 7;
	yypmatch[1] = YYCURSOR;
	yypmatch[2] = yyt1 - 4;
	yypmatch[3] = yyt1 - 2;
	yypmatch[5] = YYCURSOR - 1;
#line 149 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat("start_", group(1), "cc", group(2));
        goto end_region;
    }
#line 1705 "src/sfizz/OpcodeCleanup.cpp"
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = YYCURSOR;
		goto yy263;
	default:	goto yy34;
	}
yy241:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy265;
	default:	goto yy34;
	}
yy242:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:
		yyt2 = yyt3 = NULL;
		goto yy266;
	case '_':
		yyt3 = YYCURSOR;
		goto yy268;
	default:	goto yy34;
	}
yy243:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy270;
	default:	goto yy34;
	}
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy245;
	default:	goto yy34;
	}
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy271;
	default:	goto yy34;
	}
yy246:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy272;
	default:	goto yy34;
	}
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy245;
	default:	goto yy34;
	}
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy273;
	default:	goto yy34;
	}
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy274;
	default:	goto yy34;
	}
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy275;
	default:	goto yy34;
	}
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'q':	goto yy275;
	default:	goto yy34;
	}
yy252:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:
		yyt4 = yyt5 = NULL;
		yyt3 = YYCURSOR;
		goto yy276;
	case '_':
		yyt3 = yyt5 = YYCURSOR;
		goto yy278;
	default:	goto yy34;
	}
yy253:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy280;
	default:	goto yy34;
	}
yy254:
	++YYCURSOR;
	yynmatch = 4;
	yypmatch[2] = yyt1;
	yypmatch[4] = yyt2;
	yypmatch[6] = yyt3;
	yypmatch[0] = yyt1;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = yyt2 - 1;
	yypmatch[5] = yyt3 - 2;
	yypmatch[7] = YYCURSOR - 1;
#line 98 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat(group(1), "_", group(2), "_oncc", group(3));
        goto end_region;
    }
#line 1828 "src/sfizz/OpcodeCleanup.cpp"
yy256:
	++YYCURSOR;
	yynmatch = 3;
	yypmatch[4] = yyt1;
	yypmatch[0] = yyt1 - 8;
	yypmatch[1] = YYCURSOR;
	yypmatch[2] = yyt1 - 8;
	yypmatch[3] = yyt1 - 6;
	yypmatch[5] = YYCURSOR - 1;
#line 171 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat(group(1), "hdcc", group(2));
        goto end_region;
    }
#line 1843 "src/sfizz/OpcodeCleanup.cpp"
yy258:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy281;
	default:	goto yy34;
	}
yy259:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy237;
	default:	goto yy34;
	}
yy260:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy282;
	default:	goto yy34;
	}
yy261:
	++YYCURSOR;
	yynmatch = 3;
	yypmatch[2] = yyt1;
	yypmatch[4] = yyt2;
	yypmatch[0] = yyt1;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = yyt2 - 1;
	yypmatch[5] = YYCURSOR - 1;
#line 102 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat(group(1), "_", group(2), "1");
        goto end_region;
    }
#line 1876 "src/sfizz/OpcodeCleanup.cpp"
yy263:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy283;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy263;
	default:	goto yy34;
	}
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy285;
	default:	goto yy34;
	}
yy266:
	++YYCURSOR;
	yynmatch = 2;
	yypmatch[0] = yyt1;
	yypmatch[2] = yyt3;
	yypmatch[3] = yyt2;
	yypmatch[1] = YYCURSOR;
#line 166 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat("resonance1", group(1));
        goto end_region;
    }
#line 1911 "src/sfizz/OpcodeCleanup.cpp"
yy268:
	yych = *++YYCURSOR;
	if (yych <= 0x00) {
		yyt2 = YYCURSOR;
		goto yy266;
	}
	goto yy268;
yy270:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'k':	goto yy245;
	default:	goto yy34;
	}
yy271:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy286;
	default:	goto yy34;
	}
yy272:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy287;
	default:	goto yy34;
	}
yy273:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy288;
	default:	goto yy34;
	}
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy275;
	default:	goto yy34;
	}
yy275:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy289;
	default:	goto yy34;
	}
yy276:
	++YYCURSOR;
	yynmatch = 4;
	yypmatch[2] = yyt1;
	yypmatch[4] = yyt2;
	yypmatch[5] = yyt3;
	yypmatch[6] = yyt5;
	yypmatch[7] = yyt4;
	yypmatch[0] = yyt1;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = yyt2 - 1;
#line 110 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat(group(1), "_", group(2), "1", group(3));
        goto end_region;
    }
#line 1971 "src/sfizz/OpcodeCleanup.cpp"
yy278:
	yych = *++YYCURSOR;
	if (yych <= 0x00) {
		yyt4 = YYCURSOR;
		goto yy276;
	}
	goto yy278;
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy290;
	default:	goto yy34;
	}
yy281:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:
		yyt4 = yyt5 = NULL;
		yyt3 = YYCURSOR;
		goto yy291;
	case '_':
		yyt3 = yyt5 = YYCURSOR;
		goto yy293;
	default:	goto yy34;
	}
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy295;
	default:	goto yy34;
	}
yy283:
	++YYCURSOR;
	yynmatch = 3;
	yypmatch[4] = yyt1;
	yypmatch[0] = yyt1 - 9;
	yypmatch[1] = YYCURSOR;
	yypmatch[2] = yyt1 - 6;
	yypmatch[3] = yyt1 - 4;
	yypmatch[5] = YYCURSOR - 1;
#line 153 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat("start_", group(1), "hdcc", group(2));
        goto end_region;
    }
#line 2017 "src/sfizz/OpcodeCleanup.cpp"
yy285:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy296;
	default:	goto yy34;
	}
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt3 = YYCURSOR;
		goto yy297;
	default:	goto yy34;
	}
yy287:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy245;
	default:	goto yy34;
	}
yy288:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy245;
	default:	goto yy34;
	}
yy289:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy299;
	default:	goto yy34;
	}
yy290:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy252;
	default:	goto yy34;
	}
yy291:
	++YYCURSOR;
	yynmatch = 4;
	yypmatch[2] = yyt1;
	yypmatch[4] = yyt2;
	yypmatch[5] = yyt3;
	yypmatch[6] = yyt5;
	yypmatch[7] = yyt4;
	yypmatch[0] = yyt1;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = yyt2 - 1;
#line 106 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat(group(1), "_", group(2), "1", group(3));
        goto end_region;
    }
#line 2081 "src/sfizz/OpcodeCleanup.cpp"
yy293:
	yych = *++YYCURSOR;
	if (yych <= 0x00) {
		yyt4 = YYCURSOR;
		goto yy291;
	}
	goto yy293;
yy295:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy300;
	default:	goto yy34;
	}
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy301;
	default:	goto yy34;
	}
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy302;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy297;
	default:	goto yy34;
	}
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt3 = YYCURSOR;
		goto yy304;
	default:	goto yy34;
	}
yy300:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy281;
	default:	goto yy34;
	}
yy301:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy306;
	default:	goto yy34;
	}
yy302:
	++YYCURSOR;
	yynmatch = 4;
	yypmatch[2] = yyt1;
	yypmatch[4] = yyt2;
	yypmatch[6] = yyt3;
	yypmatch[0] = yyt1;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = yyt2 - 1;
	yypmatch[5] = yyt3 - 2;
	yypmatch[7] = YYCURSOR - 1;
#line 94 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat(group(1), "_", group(2), "_oncc", group(3));
        goto end_region;
    }
#line 2162 "src/sfizz/OpcodeCleanup.cpp"
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy307;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy304;
	default:	goto yy34;
	}
yy306:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy309;
	default:	goto yy34;
	}
yy307:
	++YYCURSOR;
	yynmatch = 4;
	yypmatch[2] = yyt1;
	yypmatch[4] = yyt2;
	yypmatch[6] = yyt3;
	yypmatch[0] = yyt1;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = yyt2 - 1;
	yypmatch[5] = yyt3 - 2;
	yypmatch[7] = YYCURSOR - 1;
#line 90 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat(group(1), "_", group(2), "_oncc", group(3));
        goto end_region;
    }
#line 2201 "src/sfizz/OpcodeCleanup.cpp"
yy309:
	yych = *++YYCURSOR;
	if (yych >= 0x01) goto yy34;
	++YYCURSOR;
	yynmatch = 1;
	yypmatch[0] = YYCURSOR - 16;
	yypmatch[1] = YYCURSOR;
#line 135 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = "group";
        goto end_region;
    }
#line 2214 "src/sfizz/OpcodeCleanup.cpp"
}
#line 180 "src/sfizz/OpcodeCleanup.re"


end_region:
    /* end */;

    } // scope == kOpcodeScopeRegion

    //--------------------------------------------------------------------------

    if (scope == kOpcodeScopeControl) {

    YYCURSOR = opcode.c_str();

    
#line 2231 "src/sfizz/OpcodeCleanup.cpp"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 's':	goto yy316;
	default:	goto yy314;
	}
yy314:
	++YYCURSOR;
yy315:
#line 200 "src/sfizz/OpcodeCleanup.re"
	{
        goto end_control;
    }
#line 2246 "src/sfizz/OpcodeCleanup.cpp"
yy316:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy317;
	default:	goto yy315;
	}
yy317:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy319;
	default:	goto yy318;
	}
yy318:
	YYCURSOR = YYMARKER;
	goto yy315;
yy319:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy320;
	default:	goto yy318;
	}
yy320:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy321;
	default:	goto yy318;
	}
yy321:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy322;
	default:	goto yy318;
	}
yy322:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy323;
	default:	goto yy318;
	}
yy323:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy324;
	default:	goto yy318;
	}
yy324:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy325;
	default:	goto yy318;
	}
yy325:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy326;
	default:	goto yy318;
	}
yy326:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = YYCURSOR;
		goto yy327;
	default:	goto yy318;
	}
yy327:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy329;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy327;
	default:	goto yy318;
	}
yy329:
	++YYCURSOR;
	yynmatch = 2;
	yypmatch[2] = yyt1;
	yypmatch[0] = yyt1 - 10;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = YYCURSOR - 1;
#line 195 "src/sfizz/OpcodeCleanup.re"
	{
        opcode = absl::StrCat("set_hdcc", group(1));
        goto end_control;
    }
#line 2349 "src/sfizz/OpcodeCleanup.cpp"
}
#line 204 "src/sfizz/OpcodeCleanup.re"


end_control:
    /* end */;

    } // scope == kOpcodeScopeControl

    //--------------------------------------------------------------------------


    #undef YYMAXNMATCH

    return opcode;
}

Opcode Opcode::cleanUp(OpcodeScope scope) const
{
    return Opcode(cleanUpOpcodeName(opcode, scope), value);
}

} // namespace sfz
