/* This file is generated by the layout maker tool. */
auto* const view__0 = createLogicalGroup(CRect(0, 0, 600, 300), -1, "", kCenterText, 14);
aboutView = view__0;
auto* const view__1 = createAboutFrame(CRect(0, 0, 600, 300), -1, "", kCenterText, 14);
view__0->addView(view__1);
auto* const view__2 = createLabel(CRect(180, 85, 425, 130), -1, "About sfizz", kCenterText, 30);
view__1->addView(view__2);
auto* const view__3 = createLabel(CRect(65, 155, 540, 200), -1, "Redtide will implement this dialog", kCenterText, 24);
view__1->addView(view__3);
